### ISSUE TITLE
LeadClientBuilder return null!!

### ISSUE THREAD

**Issue by TomySmit** [syncro/amocrm-client#1]
I get null when use LeadClientBuilder() with 0.1.3 verstion. but this bug fixed, if i turn verstion to 0.1.2.
```
LeadClientBuilder()
      .baseUrl(amoCrmHost)
      .login(amoCrmUser)
      .passwordHash(amoCrmPassword)
      .build()
```

**Comment by syncro** [comment]
well, actually it's not. My IntelliJ Debugger shows that it is null as yours, my guess this happens due to some aop magic allowed me to do auth as @nnotation, but it is not null and code works just fine. I prepared the sample app that demonstrates it by example https://github.com/syncro/amocrm-testapp
